export const PRICE = Object.freeze({
  DDAY_EVENT_INIT_DISCOUNT: 1000,
  DDAY_COUNT_PLUS_DISCOUNT: 100,
  DESSERT_DISCOUNT: 2023,
  MAIN_DISCOUNT: 2023,
  SPECIAL_EVENT_DISCOUNT_MOENY: 1000,
  GIVEAWAY_EVENT_LIMIT: 120000,
  CHAMPAGNE_PRICE: 25000,
  FOR_APPLY_EVENT: 10000,
  BADGE_STAR_MIN_BENEFIT: 5000,
  BADGE_STAR_MAX_BENEFIT: 10000,
  BADGE_TREE_MIN_BENEFIT: 10000,
  BADGE_TREE_MAX_BENEFIT: 20000,
  BADGE_SANTA_MIN_BENEFIT: 20000,
});

export const DATE = Object.freeze({
  FIRST_DAY: 1,
  LAST_DAY: 31,
  CHRISTMAS_DAY: 25,
});

export const COUNT = Object.freeze({
  MAX_ORDER: 20,
  EACH_MENU_ARR_FORM_LENGTH: 2,
});

export const ARR_INDEX = Object.freeze({
  MENU_NAME_INDEX: 0,
  MENU_AMOUNT_INDEX: 1,
  BENIFIT_LIST_TYPE_INDEX: 0,
  BEMEFIT_VALUES_INDEX: 1,
});
